### ISSUE TITLE
Searching in directory that's not called "models"

### ISSUE THREAD

**Issue by HoldYourWaffle** [Bounced-Inc/mongoose-tsgen#10]
Is it possible to put my model files in a directory that's called something other than "models" (for example "schemas")?

**Comment by francescov1** [comment]
Yes, the current path resolution looks recursively under the provided path for a "models" folder. Some sort of logic should be added to check first if the files in the provided path's directory are mongoose schemas, and if not then fallback to the current logic to recurseively search for the "models" folder. 

The recursive "models" folder search is nice because in most cases the schemas path can be found without any input and without needing to check file content for schemas. This logic is in function `getFullModelsPaths` in `src/helpers/paths.ts`. I currently don't have time to add this currently but feel free if you'd like!

**Comment by HoldYourWaffle** [comment]
What do you mean by "provided path", the working directory?

I think the easiest solution would be to have 2 simple processes:

1. The user provides a path as configuration.
We simply generate types for all schemas in this folder, without any complicated fallback mechanisms. The user has provided us with this path, so we assume the user knows what they're doing. This prevents unexpected behavior and reduces surface for future bugs. I'm not sure how checking the content of the files is relevant here however.

2. The user has not provided a path.
In this case we'll have to look for schemas ourselves, As far as I can see there's no reason to change things here, keeping the "models folder search" logic should do a fine job.

Most other CLI tools that I've used over the years do something along these lines. It's not a breaking change too, which is always nice 😄

**Comment by francescov1** [comment]
"provided path" being the first and only argument to the CLI (which defaults to the working directory).

I like your suggested approach, allows the tool to work nicely out of the box while limiting complexity with path resolution. Should be a simple enough change this way, I can look at adding it one night this week if you don't have time.
