### ISSUE TITLE
Multiple schemas in a single file

### ISSUE THREAD

**Issue by HoldYourWaffle** [Bounced-Inc/mongoose-tsgen#12]
It looks like it's currently not possible to put multiple schemas in a single "model file", because they are discovered by looking at the default export. This is not very convenient in cases where I want to group small and closely related schemas to avoid massively cluttering my file tree.

Wouldn't it be possible to instead look at all exports of a file, and "collect" all variables that have the `Schema` type?
I _think_ this should be easy using the Typescript compiler API or `ts-morph`, but it's been a while since I've used either.

**Comment by francescov1** [comment]
Yes, totally possible! This is actually something I originally planned to do but put aside as it was not high priority. There's actually a TODO in `src/helpers/tsReader.ts`, function `getModelName` that describes this (it specifically was for finding a single model in other exports if default export does not exist, but I think your suggestion makes more sense to capture **any** model exported from the file). The function grabs the entire list of exports and filters out all exports other than the default. If we return a list instead, we would also need to make a small change to `getFunctionTypes` so that it can handle more than one modelName returned from that file.

This may introduce a new requirement to validate these exports (rather than assuming they're all mongoose models) although I'm not entirely sure if that's an edge case that is common, not something I've come across. Let me know your thoughts, would love help with this if you have the time.

**Comment by HoldYourWaffle** [comment]
> although I'm not entirely sure if that's an edge case that is common, not something I've come across

Would exporting both the model and the schema trigger this "edge case"?

> would love help with this if you have the time

I would love to help out, but sadly I'm very low on time :( 
This doesn't look *too* complicated however now that I have your "pointers", so I might be able to take a shot at this relatively soon.

**Comment by francescov1** [comment]
> > although I'm not entirely sure if that's an edge case that is common, not something I've come across
> 
> Would exporting both the model and the schema trigger this "edge case"?

Exporting anything other than a model would cause an issue (since the rest of the program expects a mongoose model), the solution should be straight forward though, just need to test if the exported variable is a mongoose model.

> > would love help with this if you have the time
> 
> I would love to help out, but sadly I'm very low on time :(
> This doesn't look _too_ complicated however now that I have your "pointers", so I might be able to take a shot at this relatively soon.

Great, no stress! Im super low on time right now as well, so totally understand.

**Comment by francescov1** [comment]
Added in 7.1.0, PR #43  🚀
