### ISSUE TITLE
Add Model's static and member function signature

### ISSUE THREAD

**Issue by shivshankar3578** [Bounced-Inc/mongoose-tsgen#5]
As per example https://github.com/Bounced-Inc/mongoose-tsgen#example
 piece of generated definition
```isMetadataString: Function;``` 
should be valid signature of isMetadataString method
```isMetadataString: (this: IUser) => Boolean```

**Comment by francescov1** [comment]
Hey, I completely agree! The way the tool works, it reads in Mongoose schemas into memory (same way your app would) and infers types from the schema data. The only type we can get from that is `Function` (since TS has already been transpiled at this point). 

[ts-morph](https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph) seems like a solid option for reading the Typescript info. I can take a look at this but it likely won't be for a couple weeks, you're welcome to contribute in the meantime!
